# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "uas" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c0c705b7-a390-41d3-b195-a3985bb3e3ee";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c0c705b7-a390-41d3-b195-a3985bb3e3ee".device = "/dev/disk/by-uuid/c0c705b7-a390-41d3-b195-a3985bb3e3ee";
  boot.initrd.luks.devices."swap".device = "/dev/disk/by-uuid/d73e346e-aa84-4400-8a9f-11cff0166a24";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E333-2CD7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
