# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "thunderbolt" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-08ddcc83-d890-4e20-ae1a-85cdf34e2580";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-08ddcc83-d890-4e20-ae1a-85cdf34e2580".device = "/dev/disk/by-uuid/08ddcc83-d890-4e20-ae1a-85cdf34e2580";
  boot.initrd.luks.devices."swap".device = "/dev/disk/by-uuid/c4d1fb65-5b0c-4029-af5e-42ce3ed54f09";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/25CD-0878";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
